version: '3'

volumes:
  stack_ante:

services:
  private-gpt:
    build:
      dockerfile: Dockerfile.external
    volumes:
      - stack_ante:/home/worker/app
    ports:
      - 3500:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: external